kind: pipeline
name: Dronerino2

steps:
- name: build
  image: ubuntu:bionic

  commands:
  - apt-get update
  - apt-get install wget -y
  - ls ~
  - cd ~
  - pwd
  - rm -rf /tmp
  - df -H
  - ls -sal /home
