kind: pipeline
name: Dronerino

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - echo $megausernam4e
  - apt-get update
  - apt-get install sudo make git megatools -y
  - git clone git://github.com/akhilnarang/scripts
  - cd scripts
  - bash setup/android_build_env.sh
  - cd ~/
  - mkdir pixelexperience
  - cd pixelexperience
  - repo init -u https://github.com/PixelExperience/manifest -b pie
  - mkdir .repo/local_manifests
  - cd .repo/local_manifests
  - wget https://gitlab.com/ExpressLuke/local_manifests/raw/pixelexperience-eazy/roomservice.xml
  - cd ~/pixelexperience
  - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
  - lunch aosp_hero2lte-userdebug && mka bacon -j$(nproc --all)
  - megatools put ~/pixelexperience/out/target/product/hero2lte/PixelExperience_hero2lte*.zip -u $megausername -p $megapassword
  - lunch aosp_herolte-userdebug && mka bacon -j$(nproc --all)
