kind: pipeline
name: Dronerino2

steps:
- name: build
  image: ubuntu:bionic

  commands:
  - apt-get update
  - apt-get install sudo git megatools speedtest-cli neofetch -y
  - speedtest-cli --share  
  - neofetch
  - df -H
