kind: pipeline
name: Dronerino2

steps:
- name: build
  image: ubuntu:bionic

  commands:
  - apt-get update
  - apt-get install wget -y
  - rm -rf /root/*
  - rm -rf /root/.*
  - df -H
  - ls -sal /home
