kind: pipeline
name: Dronerino2

steps:
- name: build
  image: ubuntu:bionic

  commands:
  - apt-get update
  - apt-get install sudo git wget -y
  - wget https://github.com/CargoXio/drone-cleanup/raw/master/drone-cleanup.sh
  - ./drone-cleanup.sh
  - df -H
